name: CI Pipeline develop
on:
  workflow_dispatch:
  push:
    branches: ["develop"]
  pull_request:
    branches: [develop]

jobs:
  Sonar:
    name: Sonar
    uses: Cencosud-Cencopay/workflows/.github/workflows/sonar.yml@master
    secrets: inherit
  build:
    name: build
    needs: [sonar, get-vault-aws-credentials]
    runs-on: cencosud-helios
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
  get-vault-aws-credentials:
    name: Get AWS credentials from Vault
    uses: Cencosud-Cencopay/workflows/.github/workflows/aws-credentials.yml@master
    secrets: inherit

  build-and-push:
    name: Build and push Docker image
    needs: [build]
    runs-on: cencopay-anubis
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ needs.get-vault-aws-credentials.outputs.aws_access_key_id }}
          aws-secret-access-key: ${{ needs.get-vault-aws-credentials.outputs.aws_secret_access_key }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cw-cl-backoffice-web-manager
          IMAGE_TAG: ${{ github.sha }}
        run: |
          env
          docker build --build-arg ANGULAR_PUBLIC_ENV=${GITHUB_REF#refs/heads/} -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} .
          docker image push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY